global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fleetops-maintenance"
    metrics_path: /metrics
    static_configs:
      - targets:
          - ec2-100-54-246-160.compute-1.amazonaws.com:8080
